name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Detect app and api locations
        run: |
          # detect app directory
          if [ -f "package.json" ]; then
            APP_DIR="."
          elif [ -d "app" ]; then
            APP_DIR="app"
          elif [ -d "client" ]; then
            APP_DIR="client"
          elif [ -d "frontend" ]; then
            APP_DIR="frontend"
          elif [ -d "website" ]; then
            APP_DIR="website"
          else
            APP_DIR="."
          fi

          if [ "$APP_DIR" = "." ]; then
            echo "APP_LOCATION=/" >> $GITHUB_ENV
          else
            echo "APP_LOCATION=$APP_DIR" >> $GITHUB_ENV
          fi

          # detect api folder
          if [ -d "api" ]; then
            echo "API_LOCATION=api" >> $GITHUB_ENV
          else
            echo "API_LOCATION=" >> $GITHUB_ENV
          fi

          echo "Detected APP_LOCATION=${APP_LOCATION:-/}, API_LOCATION=${API_LOCATION:-}" 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and Build
        run: |
          # change into app folder if necessary
          if [ "${APP_LOCATION}" != "/" ]; then
            cd "${APP_LOCATION}"
          fi

          if [ -f package.json ]; then
            npm ci
          else
            echo "No package.json found in app location; skipping install"
          fi

          if npm run build --silent; then
            echo "Build succeeded"
          else
            echo "Build failed or no build script defined. If your project uses a different build command, update the workflow." >&2
            exit 1
          fi

      - name: Determine build output folder
        run: |
          # compute app dir path
          if [ "${APP_LOCATION}" = "/" ]; then
            APP_DIR_PATH="$GITHUB_WORKSPACE"
          else
            APP_DIR_PATH="$GITHUB_WORKSPACE/${APP_LOCATION}"
          fi

          if [ -d "$APP_DIR_PATH/build" ]; then
            echo "OUTPUT=build" >> $GITHUB_ENV
            OUT_DIR="$APP_DIR_PATH/build"
          elif [ -d "$APP_DIR_PATH/dist" ]; then
            echo "OUTPUT=dist" >> $GITHUB_ENV
            OUT_DIR="$APP_DIR_PATH/dist"
          else
            echo "No 'build' or 'dist' folder found after build. Directory listing for app dir:" >&2
            ls -la "$APP_DIR_PATH"
            exit 1
          fi

          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV
          echo "Detected output folder: $OUT_DIR"

      - name: Copy staticwebapp.config.json into output (if present)
        run: |
          if [ -f staticwebapp.config.json ]; then
            cp staticwebapp.config.json "$OUT_DIR/"
            echo "Copied staticwebapp.config.json into output"
          else
            echo "No staticwebapp.config.json at repo root to copy"
          fi

      - name: Upload artifact and deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # set this secret in the repo
          repo_token: ${{ secrets.GITHUB_TOKEN }} # used for GitHub integrations
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          api_location: ${{ env.API_LOCATION }}
          output_location: ${{ env.OUTPUT }}
